# Generated by Django 6.0.4 on 2026-05-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_total_cost_booking_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='city',
            field=models.CharField(choices=[('anupshahr', 'Anupshahr'), ('dibai', 'Dibai'), ('shikarpur', 'Shikarpur'), ('jahangirabad', 'Jahangirabad')], default='anupshahr', max_length=50),
        ),
    ]
